//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezGranits
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContact
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public string Type { get; set; }
        public string Contact { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
